#! /nix/store/axl12yr00f105bjqvj628f5f0s6r0cnp-bash-5.3p9/bin/bash

export PATH=/nix/store/61685rbaxmpigwi3z23i33sv3jyfl70q-coreutils-9.11/bin${PATH:+:}$PATH

set -e

# Create an empty ext4 filesystem image. A filesystem image does not
# contain a partition table but just a filesystem.
createEmptyFilesystemImage() {
  local name=$1
  local size=$2
  local temp=$(mktemp)
  /nix/store/g5gxzfrpdx1ghlw64xnhr5y39k0hf0nj-qemu-host-cpu-only-10.2.4/bin/qemu-img create -f raw "$temp" "$size"
  /nix/store/ys498nc6scmzxp5nwafgz5wfw3w1s0va-e2fsprogs-1.47.4-bin/bin/mkfs.ext4 -L nixos "$temp"
  /nix/store/g5gxzfrpdx1ghlw64xnhr5y39k0hf0nj-qemu-host-cpu-only-10.2.4/bin/qemu-img convert -f raw -O qcow2 "$temp" "$name"
  rm "$temp"
}

NIX_DISK_IMAGE=$(readlink -f "${NIX_DISK_IMAGE:-./nixos.qcow2}") || test -z "$NIX_DISK_IMAGE"

if test -n "$NIX_DISK_IMAGE" && ! test -e "$NIX_DISK_IMAGE"; then
    echo "Disk image does not exist, creating the virtualisation disk image..."

    createEmptyFilesystemImage "$NIX_DISK_IMAGE" "1024M"

    echo "Virtualisation disk image created."
fi

# Create a directory for storing temporary data of the running VM.
if [ -z "$TMPDIR" ] || [ -z "$USE_TMPDIR" ]; then
    TMPDIR=$(mktemp -d nix-vm.XXXXXXXXXX --tmpdir)
fi



# Create a directory for exchanging data with the VM.
mkdir -p "$TMPDIR/xchg"







cd "$TMPDIR"





# Start QEMU.
exec /nix/store/g5gxzfrpdx1ghlw64xnhr5y39k0hf0nj-qemu-host-cpu-only-10.2.4/bin/qemu-system-x86_64 -machine accel=kvm:tcg -cpu max \
    -name nixos \
    -m 1024 \
    -smp 1 \
    -device virtio-rng-pci \
    -net nic,netdev=user.0,model=virtio -netdev user,id=user.0,"$QEMU_NET_OPTS" \
    -virtfs local,path=/nix/store,security_model=none,mount_tag=nix-store \
    -virtfs local,path="${SHARED_DIR:-$TMPDIR/xchg}",security_model=none,mount_tag=shared \
    -virtfs local,path="$TMPDIR"/xchg,security_model=none,mount_tag=xchg \
    -drive cache=writeback,file="$NIX_DISK_IMAGE",id=drive1,if=none,index=1,werror=report -device virtio-blk-pci,bootindex=1,drive=drive1,serial=root \
    -device virtio-keyboard \
    -usb \
    -device usb-tablet,bus=usb-bus.0 \
    -kernel ${NIXPKGS_QEMU_KERNEL_nixos:-/nix/store/8nv0c0jgvhdhvb1vj8q5f94sigc7pdr0-nixos-system-nixos-26.05.20260916.4c78701/kernel} \
    -initrd /nix/store/pqrijcl7na7vrhr4dfcdwpqlda3shx2q-initrd-linux-7.2.6/initrd \
    -append "$(cat /nix/store/8nv0c0jgvhdhvb1vj8q5f94sigc7pdr0-nixos-system-nixos-26.05.20260916.4c78701/kernel-params) init=/nix/store/8nv0c0jgvhdhvb1vj8q5f94sigc7pdr0-nixos-system-nixos-26.05.20260916.4c78701/init regInfo=/nix/store/hc7kiq36j4damrw68d2q2cx97z5782rq-closure-info/registration console=ttyS0,115200n8 console=tty0 $QEMU_KERNEL_PARAMS" \
    $QEMU_OPTS \
    "$@"
